version: 2
registries:
  composer-repository-nova-laravel-com:
    type: composer-repository
    url: https://nova.laravel.com
    username: mailtokmahmed@gmail.com
    password: "${{secrets.COMPOSER_REPOSITORY_NOVA_LARAVEL_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: orchestra/testbench
    versions:
    - 6.12.0
    - 6.14.0
    - 6.16.0
  - dependency-name: vimeo/psalm
    versions:
    - 4.5.0
    - 4.5.1
  registries:
  - composer-repository-nova-laravel-com
